sudo: false
language: python
cache: pip
services:
  - docker

install:
  - make install

env:
  - TMPDIR=/home/travis/build/saltstack/saltdocker

python:
  - '3.7-dev'

script:
  - make lint
  - make build

deploy:
  provider: script
  script: make push
  on:
    branch: master
